-- +goose Up
CREATE TABLE pitches (
  game_pk INTEGER NOT NULL,
  game_date TEXT,
  at_bat_number INTEGER,
  pitch_number INTEGER,
  pitcher_id INTEGER REFERENCES players (id),
  batter_id INTEGER REFERENCES players (id),
  home_team TEXT,
  away_team TEXT,
  inning INTEGER,
  inning_topbot TEXT, --"Top" || "Bot"
  balls INTEGER,
  strikes INTEGER,
  outs_when_up INTEGER,
  on_1b INTEGER,
  on_2b INTEGER,
  on_3b INTEGER,
  fielder_2 INTEGER,
  fielder_3 INTEGER,
  fielder_4 INTEGER,
  fielder_5 INTEGER,
  fielder_6 INTEGER,
  fielder_7 INTEGER,
  fielder_8 INTEGER,
  fielder_9 INTEGER,
  stand TEXT, -- "R" || "L"
  pitch_type TEXT,
  release_speed FLOAT,
  effective_speed FLOAT,
  release_spin_rate INTEGER,
  spin_axis INTEGER,
  pfx_x FLOAT,
  pfx_z FLOAT,
  plate_x FLOAT,
  plate_z FLOAT,
  zone INTEGER,
  release_extension FLOAT,
  events TEXT,
  description TEXT,
  bb_type TEXT,
  launch_speed FLOAT,
  launch_angle INTEGER,
  hit_distance_sc INTEGER,
  estimated_ba_using_speedangle FLOAT,
  estimated_woba_using_speedangle FLOAT,
  woba_value FLOAT,
  woba_denom INTEGER,
  babip_value INTEGER,
  delta_run_exp FLOAT,
  delta_win_exp FLOAT,
  PRIMARY KEY (game_pk, at_bat_number, pitch_number)
);

-- +goose Down
DROP TABLE pitches;
